/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Question;

import Entity.Question;
import Work.Check;
import java.awt.event.ItemEvent;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HuyHung
 */
public class PanelQuestion extends javax.swing.JPanel {

    /**
     * Creates new form PanelSinhVien
     */
    private int iSearch = 0;
    private boolean addOrUpdate = true;
    private String idSubject;
    private Vector<Question> vtQuesSearch = new Vector<>();
    private Vector<Question> vtQuestion = null;
    private Check check = new Check();
    private QuestionDAO questionDAO = new QuestionDAO();
    private DefaultTableModel model = new DefaultTableModel() {
        @Override
        public boolean isCellEditable(int rowIndex, int columnIndex) {
            return false;
        }
    };

    public PanelQuestion(String idSubject) {
        initComponents();
        tbQuestion.setEditingRow(1);
        this.idSubject = idSubject;
        loadColumnData();
        loadRowData(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel14 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        cbSelect = new javax.swing.JComboBox();
        tfSearch = new javax.swing.JTextField();
        btSearch = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbQuestion = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tfCorrect = new javax.swing.JTextField();
        btCancel = new javax.swing.JButton();
        btOK = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        taC = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        taD = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        taB = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        taQuestion = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        taA = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        cbLevel = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        tfID = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        btAdd = new javax.swing.JButton();
        btUpdate = new javax.swing.JButton();
        btDelete = new javax.swing.JButton();
        btRefresh = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("FACULTY INFORMATION");

        setPreferredSize(new java.awt.Dimension(750, 383));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tìm Kiếm", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP));

        cbSelect.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "[--Chọn một--]", "Theo ID", "Theo Nội dung" }));
        cbSelect.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbSelectItemStateChanged(evt);
            }
        });
        cbSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSelectActionPerformed(evt);
            }
        });

        tfSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfSearchKeyReleased(evt);
            }
        });

        btSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Search.png"))); // NOI18N
        btSearch.setText("Tìm Kiếm");
        btSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tfSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        tbQuestion.setAutoCreateRowSorter(true);
        tbQuestion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "STT", "Mã Môn Học", "Số Tiết", "Học Kì", "Hình Thức Thi"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbQuestion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbQuestionMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tbQuestionMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tbQuestion);
        if (tbQuestion.getColumnModel().getColumnCount() > 0) {
            tbQuestion.getColumnModel().getColumn(0).setMaxWidth(350);
            tbQuestion.getColumnModel().getColumn(2).setMaxWidth(200);
            tbQuestion.getColumnModel().getColumn(4).setMaxWidth(300);
        }

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 204)));
        jPanel2.setForeground(new java.awt.Color(153, 153, 255));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 204));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("ID");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 204));
        jLabel2.setText("Câu hỏi");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setText("Đáp án A:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 204));
        jLabel7.setText("Đáp án C:");

        tfCorrect.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        btCancel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btCancel.setForeground(new java.awt.Color(255, 0, 0));
        btCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/cancel.png"))); // NOI18N
        btCancel.setText("Cancel");
        btCancel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelActionPerformed(evt);
            }
        });

        btOK.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btOK.setForeground(new java.awt.Color(255, 0, 0));
        btOK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/accept.png"))); // NOI18N
        btOK.setText("OK");
        btOK.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btOKActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 204));
        jLabel9.setText("Đáp án D:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 204));
        jLabel3.setText("Đáp án B:");

        taC.setColumns(20);
        taC.setLineWrap(true);
        taC.setRows(5);
        taC.setWrapStyleWord(true);
        jScrollPane2.setViewportView(taC);

        taD.setColumns(20);
        taD.setLineWrap(true);
        taD.setRows(5);
        taD.setWrapStyleWord(true);
        jScrollPane3.setViewportView(taD);

        taB.setColumns(20);
        taB.setLineWrap(true);
        taB.setRows(5);
        taB.setWrapStyleWord(true);
        jScrollPane4.setViewportView(taB);

        taQuestion.setColumns(20);
        taQuestion.setLineWrap(true);
        taQuestion.setRows(5);
        taQuestion.setWrapStyleWord(true);
        jScrollPane5.setViewportView(taQuestion);

        taA.setColumns(20);
        taA.setLineWrap(true);
        taA.setRows(5);
        taA.setWrapStyleWord(true);
        jScrollPane6.setViewportView(taA);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 204));
        jLabel10.setText("Level:");

        cbLevel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cbLevel.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Dễ", "Trung Bình", "Khó" }));
        cbLevel.setAlignmentX(1.5F);
        cbLevel.setAlignmentY(1.5F);
        cbLevel.setName(""); // NOI18N
        cbLevel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbLevelActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 204));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Đáp án");

        tfID.setEnabled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel2)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                            .addComponent(jScrollPane6))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tfID, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tfCorrect, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jLabel10)
                .addGap(10, 10, 10)
                .addComponent(cbLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btOK)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btCancel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jScrollPane3, jScrollPane4});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(9, 9, 9)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(tfCorrect, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btOK)
                        .addComponent(btCancel))
                    .addComponent(jLabel10)
                    .addComponent(cbLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(tfID, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13))
        );

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 204)));

        btAdd.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btAdd.setForeground(new java.awt.Color(255, 0, 0));
        btAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/new.png"))); // NOI18N
        btAdd.setText("Add");
        btAdd.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddActionPerformed(evt);
            }
        });

        btUpdate.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btUpdate.setForeground(new java.awt.Color(255, 0, 0));
        btUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/save.png"))); // NOI18N
        btUpdate.setText("Update");
        btUpdate.setEnabled(false);
        btUpdate.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btUpdateActionPerformed(evt);
            }
        });

        btDelete.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btDelete.setForeground(new java.awt.Color(255, 0, 0));
        btDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Remove.png"))); // NOI18N
        btDelete.setText("Delete");
        btDelete.setEnabled(false);
        btDelete.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btDelete.setIconTextGap(2);
        btDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDeleteActionPerformed(evt);
            }
        });

        btRefresh.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btRefresh.setForeground(new java.awt.Color(255, 0, 0));
        btRefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Refresh.png"))); // NOI18N
        btRefresh.setText("Refresh");
        btRefresh.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btRefresh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(btAdd)
                .addGap(8, 8, 8)
                .addComponent(btUpdate)
                .addGap(8, 8, 8)
                .addComponent(btDelete)
                .addGap(8, 8, 8)
                .addComponent(btRefresh)
                .addContainerGap())
        );

        jLabel15.setBackground(new java.awt.Color(0, 0, 255));
        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 255));
        jLabel15.setText("Manage Question");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 617, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel15)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void loadColumnData() {
        Vector<String> columnName = questionDAO.getColumnName();
        columnName.add(0, "STT");
        columnName.remove(1);
        columnName.remove(columnName.size() - 1);
        model.setColumnIdentifiers(columnName);
    }

    private void loadRowData(int i) {
        removeRow();
        setEnableInput(false);
        setEnableButton2(false);
        int stt = 0;
        switch (i) {
            //Load data question
            case 0:
                vtQuestion = questionDAO.getRowData(idSubject);
                for (Question a : vtQuestion) {
                    stt++;
                    model.addRow(toObjectData(stt, a));
                }
                break;
            // Load data from box search.
            case 1:
                for (Question a : vtQuesSearch) {
                    stt++;
                    model.addRow(toObjectData(stt, a));
                }
                break;
            default:
                show("Sai chỉ số", 0);
                return;
        }
        tbQuestion.setModel(model);

    }

    private void setEnableInput(boolean kt) {
        taQuestion.setEnabled(kt);
        taA.setEnabled(kt);
        taB.setEnabled(kt);
        taC.setEnabled(kt);
        taD.setEnabled(kt);
        tfCorrect.setEnabled(kt);
        cbLevel.setEnabled(kt);
    }

    private void setEditInput(boolean kt) {
        taQuestion.setEditable(kt);
        taA.setEditable(kt);
        taB.setEditable(kt);
        taC.setEditable(kt);
        taD.setEditable(kt);
        tfCorrect.setEditable(kt);
        cbLevel.setEditable(kt);
    }

    private void setEnableButton(boolean kt) {
        btAdd.setEnabled(kt);
        btUpdate.setEnabled(kt);
        btDelete.setEnabled(kt);
    }

    private void setEnableButton2(boolean kt) {
        btOK.setEnabled(kt);
        btCancel.setEnabled(kt);
    }

    private void resetTextfiel() {
        taQuestion.setText("");
        taA.setText("");
        taB.setText("");
        taC.setText("");
        taD.setText("");
        tfCorrect.setText("");
        tfID.setText("");
        cbLevel.setSelectedItem(1);
    }

    private void removeRow() {
        //Xóa dữ liệu hiện tại
        while (model.getRowCount() > 0) {
            model.removeRow(0);
        }
    }

    private Object[] toObjectData(int stt, Question ques) {
        Object[] obj = {stt, ques.getQuestion(), ques.getAnswerA(), ques.getAnswerB(),
            ques.getAnswerC(), ques.getAnswerD(), ques.getCorrect(), ques.getLevel()};
        return obj;
    }

    private boolean addOrUpdate(boolean add, Question ques) {
        // Button add
        if (add) {
            if (questionDAO.checkIDQuestion(ques.getID())) {
                show("Thêm mới không thành công!\n<html>Câu hỏi: <b>" + ques.getID()
                        + "</b> đã tồn tại.\nVui lòng thử lại.", 0);
                return false;
            } else {
                questionDAO.addQuestion(ques);
                return true;
            }
            // Button update
        } else {
            if (!questionDAO.checkIDQuestion(ques.getID())) {
                show("Cập nhật không thành công!\n<html>Câu hỏi: <b>" + ques.getID()
                        + "</b> không có trong hệ thống.\nVui lòng thử lại.", 0);
                return false;
            } else {
                questionDAO.updateQuestion(ques);
                return true;
            }
        }
    }

    private void cbSelectItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbSelectItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            iSearch = cbSelect.getSelectedIndex();
        }
    }//GEN-LAST:event_cbSelectItemStateChanged

    private void cbSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSelectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbSelectActionPerformed

    private void btSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSearchActionPerformed
        if (tfSearch.getText().equals("")) {
            show("Khung tìm kiếm không được để trống.", 0);
        } else {
            if (iSearch == 0) {
                show("Vui lòng chọn chế độ tìm kiếm.", 0);
            } else {
                System.out.println(iSearch);
                // search(iSearch, tfSearch.getText().trim());
            }
        }
    }//GEN-LAST:event_btSearchActionPerformed


    private void tbQuestionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbQuestionMouseClicked

    }//GEN-LAST:event_tbQuestionMouseClicked


    private void tbQuestionMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbQuestionMouseReleased
        setEnableButton(true);
        setEnableButton2(false);
        setEnableInput(true);
        setEditInput(false);

        int indexRow = tbQuestion.getSelectedRow();
        tfID.setText(vtQuestion.get(indexRow).getID());
        taQuestion.setText(tbQuestion.getValueAt(indexRow, 1).toString());
        taA.setText(tbQuestion.getValueAt(indexRow, 2).toString());
        taB.setText(tbQuestion.getValueAt(indexRow, 3).toString());
        taC.setText(tbQuestion.getValueAt(indexRow, 4).toString());
        taD.setText(tbQuestion.getValueAt(indexRow, 5).toString());
        tfCorrect.setText(tbQuestion.getValueAt(indexRow, 6).toString());
        cbLevel.setSelectedItem(tbQuestion.getValueAt(indexRow, 7).toString());
    }//GEN-LAST:event_tbQuestionMouseReleased


    private void btAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddActionPerformed
        setEnableInput(true);
        setEnableButton(false);
        resetTextfiel();
        setEditInput(true);
        setEnableButton2(true);
        tfID.setText(getRandomID());
        addOrUpdate = true;
    }//GEN-LAST:event_btAddActionPerformed

    private String getRandomID() {
        int id = Integer.parseInt(vtQuestion.lastElement().getID().substring(3)) + 1;
        String idQues = idSubject;
        if (id < 10) {
            idQues += "00" + id;
        } else if (id < 100) {
            idQues += "0" + id;
        } else {
            idQues += id;
        }
        System.out.println(idSubject + "_:_" + idQues);
        return idQues;
    }

    private void btUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btUpdateActionPerformed
        setEnableInput(true);
        setEnableButton(false);
        setEnableButton2(true);
        setEditInput(true);
        addOrUpdate = false;
    }//GEN-LAST:event_btUpdateActionPerformed

    private void btDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDeleteActionPerformed
        String ID = tfID.getText().trim();
        ID = idSubject + ID;
        int b = JOptionPane.showConfirmDialog(null, "<html>Bạn có chắc chắn muốn xóa câu hỏi <b>" + ID + " ??", "Thông Báo", JOptionPane.YES_NO_OPTION);
        if (b == JOptionPane.YES_OPTION) {
            if (questionDAO.delQuestion(ID)) {
                show("Xóa thành công !", 1);
                btRefresh.doClick();
            } else {
                show("Xóa không thành công !", 0);
            }
        }
    }//GEN-LAST:event_btDeleteActionPerformed

    private void btRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRefreshActionPerformed
        loadRowData(0);
        setEnableInput(false);
        setEnableButton(false);
        setEnableButton2(false);
        setEditInput(false);
        resetTextfiel();

        btAdd.setEnabled(true);

    }//GEN-LAST:event_btRefreshActionPerformed

    private void btOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btOKActionPerformed

        String ques = taQuestion.getText().trim();
        String ansA = taA.getText().trim();
        String ansB = taB.getText().trim();
        String ansC = taC.getText().trim();
        String ansD = taD.getText().trim();
        String correct = tfCorrect.getText().trim();
        String level = cbLevel.getSelectedItem().toString();

        if (check.checkString(ques) && check.checkString(ansA) && check.checkString(ansB)
                && check.checkString(ansC) && check.checkString(ansD) && check.checkString(correct)) {
            // Add
            if (addOrUpdate) {
                Question que = new Question(tfID.getText().trim(), ques, ansA, ansB, ansC, ansD, correct, level, idSubject);
                if (addOrUpdate(true, que)) {
                    show("Thêm mới thành công!\n", 1);
                }
                // Update
            } else {
                Question que = new Question(tfID.getText().trim(), ques, ansA, ansB, ansC, ansD, correct, level);
                if (addOrUpdate(false, que)) {
                    show("Cập nhật thành công!\n", 1);
                }
            }
            btRefresh.doClick();
        } else {
            show("Phải điền đầy đủ thông tin.", 0);
        }


    }//GEN-LAST:event_btOKActionPerformed

    private void btCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelActionPerformed
        setEnableInput(false);
        setEnableButton(true);
        setEnableButton2(false);
        resetTextfiel();
    }//GEN-LAST:event_btCancelActionPerformed

    private void cbLevelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbLevelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbLevelActionPerformed

    private void tfSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfSearchKeyReleased
        if (iSearch != 0) {
            String keyword = tfSearch.getText().trim();
            vtQuesSearch.removeAllElements();
            if (iSearch == 1) {
                for (Question ques : vtQuestion) {
                    if (ques.getID().toLowerCase().contains(keyword.toLowerCase())) {
                        vtQuesSearch.add(ques);
                    }
                }
            } else {
                for (Question ques : vtQuestion) {
                    if (ques.getQuestion().toLowerCase().contains(keyword.toLowerCase())) {
                        vtQuesSearch.add(ques);
                    }
                }
            }
            if (vtQuesSearch.size() != 0) {
                loadRowData(1);
            }
        } else {
            show("Bạn cần chọn chế độ tìm kiếm", 0);
        }
    }//GEN-LAST:event_tfSearchKeyReleased
    private void show(String msg, int option) {
        JOptionPane.showMessageDialog(null, msg, "  Thông báo", option);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAdd;
    private javax.swing.JButton btCancel;
    private javax.swing.JButton btDelete;
    private javax.swing.JButton btOK;
    private javax.swing.JButton btRefresh;
    private javax.swing.JButton btSearch;
    private javax.swing.JButton btUpdate;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox cbLevel;
    private javax.swing.JComboBox cbSelect;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTextArea taA;
    private javax.swing.JTextArea taB;
    private javax.swing.JTextArea taC;
    private javax.swing.JTextArea taD;
    private javax.swing.JTextArea taQuestion;
    private javax.swing.JTable tbQuestion;
    private javax.swing.JTextField tfCorrect;
    private javax.swing.JTextField tfID;
    private javax.swing.JTextField tfSearch;
    // End of variables declaration//GEN-END:variables
}
