/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import ProcessSocket.Client;
import Entity.Account;
import Entity.History;
import Entity.Question;
import Entity.Register;
import Reports.Report;
import Work.DateTime;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Vector;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Huy Hung
 */
public class frmMain extends javax.swing.JFrame {

    public static String subject = "";
    public static String level = "";

    private Vector<History> vtHistory = new Vector<History>();
    private DefaultTableModel model = new DefaultTableModel() {
        @Override
        public boolean isCellEditable(int rowIndex, int columnIndex) {
            return false;
        }
    };

    private Client client;
    private Account acc = new Account();

    public final int MAX = 10;
    private JLabel[] label = new JLabel[4 * MAX + 1];
    private JPanel[] pnlMain = new JPanel[MAX];

    public frmMain(Client client, Account acc) {
        this.client = client;
        this.acc = acc;
        initComponents();
        setLocation(380, 100);
        setResizable(false);
        setLabel();
        setTime();
        loadColumnData();
        loadRowData();
//        loadHistory();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pToday = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lbToday = new javax.swing.JLabel();
        lbCurrentTime = new javax.swing.JLabel();
        pInfo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lbUsername = new javax.swing.JLabel();
        lbName = new javax.swing.JLabel();
        lbLastLogIn = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tpMenu = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        lbNum = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbHistory = new javax.swing.JTable();
        jLabel15 = new javax.swing.JLabel();
        cbSubjectHistory = new javax.swing.JComboBox();
        btPrint = new javax.swing.JButton();
        btUpdate = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tpText = new javax.swing.JTextPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        cbSubject = new javax.swing.JComboBox();
        jLabel14 = new javax.swing.JLabel();
        cbLevel = new javax.swing.JComboBox();
        btStart = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        miLogout = new javax.swing.JMenuItem();
        miRegister = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        miExit = new javax.swing.JMenuItem();
        mAbout = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        pToday.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin hệ thống", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 1, 14), new java.awt.Color(0, 51, 204))); // NOI18N
        pToday.setForeground(new java.awt.Color(0, 51, 255));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 255));
        jLabel4.setText("Ngày: ");

        jLabel10.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 51, 255));
        jLabel10.setText("Giờ: ");

        lbToday.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lbToday.setForeground(new java.awt.Color(0, 102, 0));
        lbToday.setText("Day");

        lbCurrentTime.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbCurrentTime.setForeground(new java.awt.Color(0, 102, 0));
        lbCurrentTime.setText("Time");

        javax.swing.GroupLayout pTodayLayout = new javax.swing.GroupLayout(pToday);
        pToday.setLayout(pTodayLayout);
        pTodayLayout.setHorizontalGroup(
            pTodayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pTodayLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pTodayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pTodayLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(lbCurrentTime))
                    .addGroup(pTodayLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbToday)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pTodayLayout.setVerticalGroup(
            pTodayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pTodayLayout.createSequentialGroup()
                .addGap(0, 11, Short.MAX_VALUE)
                .addGroup(pTodayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lbToday))
                .addGap(18, 18, 18)
                .addGroup(pTodayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(lbCurrentTime))
                .addContainerGap())
        );

        pInfo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin tài khoản", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 1, 14), new java.awt.Color(0, 51, 204))); // NOI18N
        pInfo.setForeground(new java.awt.Color(0, 51, 255));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 255));
        jLabel1.setText("Full name:");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 255));
        jLabel3.setText("Lần cuối đăng nhập: ");

        jLabel7.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 51, 255));
        jLabel7.setText("Tài khoản:");

        lbUsername.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lbUsername.setForeground(new java.awt.Color(255, 0, 0));
        lbUsername.setText("username");

        lbName.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lbName.setForeground(new java.awt.Color(255, 0, 0));
        lbName.setText("name");

        lbLastLogIn.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lbLastLogIn.setForeground(new java.awt.Color(0, 102, 0));
        lbLastLogIn.setText("Last Log In");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/user-group.png"))); // NOI18N
        jLabel2.setText(" ");

        javax.swing.GroupLayout pInfoLayout = new javax.swing.GroupLayout(pInfo);
        pInfo.setLayout(pInfoLayout);
        pInfoLayout.setHorizontalGroup(
            pInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pInfoLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jLabel6)
                .addGap(0, 108, Short.MAX_VALUE))
            .addGroup(pInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(pInfoLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(lbName))
                    .addGroup(pInfoLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(lbUsername))
                    .addGroup(pInfoLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lbLastLogIn))
                    .addComponent(jLabel2))
                .addContainerGap())
        );
        pInfoLayout.setVerticalGroup(
            pInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lbUsername))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lbName))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(5, 5, 5)
                .addComponent(lbLastLogIn)
                .addGap(0, 0, 0)
                .addComponent(jLabel6)
                .addGap(3, 3, 3)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        tpMenu.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        tpMenu.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel9.setText("Số bài thi đã làm:");

        lbNum.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lbNum.setForeground(new java.awt.Color(255, 0, 0));
        lbNum.setText("5");

        tbHistory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbHistory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tbHistoryMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tbHistory);

        jLabel15.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel15.setText("Hiển thị theo môn thi:");

        cbSubjectHistory.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "[---Tất cả---]", "Tiếng Anh", "Mạng Máy Tính" }));
        cbSubjectHistory.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cbSubjectHistory.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbSubjectHistoryItemStateChanged(evt);
            }
        });

        btPrint.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btPrint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/printer_3.png"))); // NOI18N
        btPrint.setText("In chi tiết");
        btPrint.setEnabled(false);
        btPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPrintActionPerformed(evt);
            }
        });

        btUpdate.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Refresh.png"))); // NOI18N
        btUpdate.setText("Cập nhật");
        btUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btPrint)
                .addGap(18, 18, 18)
                .addComponent(btUpdate)
                .addGap(131, 131, 131))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel16))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lbNum)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(18, 18, 18)
                        .addComponent(cbSubjectHistory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(lbNum))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbSubjectHistory, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btUpdate)
                    .addComponent(btPrint)))
        );

        tpMenu.addTab("Lịch sử làm bài thi", jPanel2);

        tpText.setBackground(new java.awt.Color(204, 204, 255));
        tpText.setFont(new java.awt.Font("Arial", 2, 12)); // NOI18N
        tpText.setForeground(new java.awt.Color(0, 102, 204));
        tpText.setText("Lưu ý: \n- Chọn môn thi, mức độ khó của đề.\n- Mỗi đề gồm 10 câu hỏi và thời gian làm bài là 15 phút.\n- Thời gian làm bài sẽ được tính kể từ lúc bạn nhấn vào nút \"Bắt đầu\".");
        tpText.setVerifyInputWhenFocusTarget(false);
        jScrollPane2.setViewportView(tpText);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, null, new java.awt.Color(204, 204, 255)));

        jLabel13.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel13.setText("Môn thi:");

        cbSubject.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "[---Danh sách môn---]", "Tiếng Anh", "Mạng máy tính" }));

        jLabel14.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel14.setText("Độ khó:");

        cbLevel.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "[---Mức độ---]", "Dễ", "Trung Bình", "Khó" }));

        btStart.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btStart.setText("Bắt đầu");
        btStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btStartActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(btStart)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbSubject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(83, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(jLabel14))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cbSubject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cbLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(btStart)
                .addGap(51, 51, 51))
        );

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Test-icon.png"))); // NOI18N
        jLabel5.setText(" ");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 474, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8)
                        .addGap(0, 0, 0)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel8))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        tpMenu.addTab("Làm bài thi mới", jPanel3);

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/system_1.png"))); // NOI18N
        jMenu1.setText("System");

        miLogout.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        miLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/logout.png"))); // NOI18N
        miLogout.setText("Đăng xuất");
        miLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miLogoutActionPerformed(evt);
            }
        });
        jMenu1.add(miLogout);

        miRegister.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        miRegister.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/register.png"))); // NOI18N
        miRegister.setText("Đổi mật khẩu");
        miRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miRegisterActionPerformed(evt);
            }
        });
        jMenu1.add(miRegister);
        jMenu1.add(jSeparator1);

        miExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        miExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/exit.png"))); // NOI18N
        miExit.setText("Exit");
        miExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miExitActionPerformed(evt);
            }
        });
        jMenu1.add(miExit);

        jMenuBar1.add(jMenu1);

        mAbout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/help.png"))); // NOI18N
        mAbout.setText("Help");
        mAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mAboutActionPerformed(evt);
            }
        });

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/about.png"))); // NOI18N
        jMenuItem1.setText("About");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        mAbout.add(jMenuItem1);

        jMenuBar1.add(mAbout);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pToday, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tpMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 503, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(tpMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(pInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(2, 2, 2)
                        .addComponent(pToday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void setLabel() {
        tpText.setEditable(false);
        lbUsername.setText(acc.getUsername());
        lbName.setText(acc.getFullname());
        lbLastLogIn.setText(acc.getLastTimeLogin());
    }

    private void setTime() {
        lbToday.setText(DateTime.getToday());

        Timer clock = new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                lbCurrentTime.setText(DateTime.getTime());
            }
        });
        clock.start();
    }

    private void loadColumnData() {
        Vector<String> columnName = new Vector();
        columnName.add(0, "STT");
        columnName.add(1, "Môn thi");
        columnName.add(2, "Độ khó");
        columnName.add(3, "Thời gian");
        columnName.add(4, "Điểm");
        model.setColumnIdentifiers(columnName);
    }

    private void loadRowData() {
        int stt = 0;
        removeRow();
        vtHistory = client.reqHistory(acc.getUsername());
        int num = vtHistory.size();
        if (num > 0) {
            lbNum.setText(num + "");
        } else {
            lbNum.setText("0");
        }

        for (History hs : vtHistory) {
            stt++;
            model.addRow(toObjectData(stt, hs));
        }
        tbHistory.setModel(model);
    }

    private void removeRow() {
        //Xóa dữ liệu hiện tại
        while (model.getRowCount() > 0) {
            model.removeRow(0);
        }
    }

    private Object[] toObjectData(int stt, History hs) {
        Object[] obj = {stt, hs.getNameSubject(), hs.getLevel(), hs.getTimeTask(), hs.getTotal()};
        return obj;
    }

    private void exit() {
        int choice = JOptionPane.showConfirmDialog(null, "Bạn thực sự muốn thoát?", "   Thoát", JOptionPane.YES_NO_OPTION, 3);
        if (choice == JOptionPane.YES_OPTION) {
            client.reqLogout(lbUsername.getText());
            System.exit(0);
        }
    }

    private void miExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miExitActionPerformed
        exit();
    }//GEN-LAST:event_miExitActionPerformed

    private void btStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btStartActionPerformed
        int choice = JOptionPane.showConfirmDialog(null, "Bạn đã sẵn sàng chưa? ", "   Làm bài thi", JOptionPane.YES_NO_OPTION, 3);
        if (choice == JOptionPane.YES_OPTION) {
            if (!client.isOnline()) {
                JOptionPane.showMessageDialog(null, "Kết nối đến server bị ngắt.\nVui lòng đăng nhập lại.", "   Error", 0);
                this.dispose();
                new frmLogin().setVisible(true);
            } else {
                subject = cbSubject.getSelectedItem().toString();
                int indexSubject = cbSubject.getSelectedIndex();
                String idSubject = "ENG";
                switch (indexSubject) {
                    case 1:
                        idSubject = "ENG";
                        break;
                    case 2:
                        idSubject = "MMT";
                        break;
                    default:
                        JOptionPane.showMessageDialog(null, "Bạn không biết mình nên thi môn nào sao???", "   Error", 0);
                        return;
                }
                int indexLevel = cbLevel.getSelectedIndex();
                if (indexLevel != 0) {
                    level = cbLevel.getItemAt(indexLevel).toString();
                } else {
                    JOptionPane.showMessageDialog(null, "Bạn chưa chọn độ khó kìa", "   Error", 0);
                    return;
                }
                Register register = new Register("a", acc.getUsername(), idSubject, level);
                Vector<Question> vtQuestions = client.reqQuestion(register);
                int i = 1;
                for (Question x : vtQuestions) {
                    System.out.println("Câu " + i++ + ": " + x.getCorrect());
                }
                this.setVisible(false);
                new frmTest(client, this, vtQuestions).setVisible(true);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Tôi biết bạn là kẻ nhát gan.");

        }
    }//GEN-LAST:event_btStartActionPerformed

    private void miLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miLogoutActionPerformed
        this.dispose();
        client.reqLogout(lbUsername.getText());
        new frmLogin().setVisible(true);
    }//GEN-LAST:event_miLogoutActionPerformed

    private void miRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miRegisterActionPerformed
        new frmChangePWD(client, acc).setVisible(true);
    }//GEN-LAST:event_miRegisterActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        exit();
    }//GEN-LAST:event_formWindowClosing

    private void btUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btUpdateActionPerformed
        btPrint.setEnabled(false);
        loadRowData();
    }//GEN-LAST:event_btUpdateActionPerformed

    private void cbSubjectHistoryItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbSubjectHistoryItemStateChanged
        if (cbSubjectHistory.getSelectedIndex() != 0) {
            removeRow();
            int stt = 0;
            for (History hs : vtHistory) {
                if (hs.getNameSubject().equalsIgnoreCase(cbSubjectHistory.getSelectedItem().toString())) {
                    stt++;
                    model.addRow(toObjectData(stt, hs));
                }
            }
            if (stt == 0) {
                JOptionPane.showMessageDialog(null, "Bạn chưa thi môn này lần nào.", "Thông báo", 1);
            }
            tbHistory.setModel(model);
        } else {
            loadRowData();
        }
    }//GEN-LAST:event_cbSubjectHistoryItemStateChanged

    private void mAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mAboutActionPerformed

    }//GEN-LAST:event_mAboutActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        new AboutMe().setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void tbHistoryMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbHistoryMouseReleased
        btPrint.setEnabled(true);
    }//GEN-LAST:event_tbHistoryMouseReleased

    private void btPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPrintActionPerformed
        int idTask = vtHistory.get(tbHistory.getSelectedRow()).getIdTask();
        String subject = tbHistory.getValueAt(tbHistory.getSelectedRow(), 1).toString();
        String level = tbHistory.getValueAt(tbHistory.getSelectedRow(), 2).toString();
        String time = tbHistory.getValueAt(tbHistory.getSelectedRow(), 3).toString();
        int total = Integer.parseInt(tbHistory.getValueAt(tbHistory.getSelectedRow(), 4).toString());
        new Report(client, idTask, lbName.getText(), subject, level, time, total).createReport();
    }//GEN-LAST:event_btPrintActionPerformed
    public String getUsername() {
        return acc.getUsername();
    }

    public String getFullname() {
        return acc.getFullname();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btPrint;
    private javax.swing.JButton btStart;
    private javax.swing.JButton btUpdate;
    private javax.swing.JComboBox cbLevel;
    private javax.swing.JComboBox cbSubject;
    private javax.swing.JComboBox cbSubjectHistory;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JLabel lbCurrentTime;
    private javax.swing.JLabel lbLastLogIn;
    private javax.swing.JLabel lbName;
    private javax.swing.JLabel lbNum;
    private javax.swing.JLabel lbToday;
    private javax.swing.JLabel lbUsername;
    private javax.swing.JMenu mAbout;
    private javax.swing.JMenuItem miExit;
    private javax.swing.JMenuItem miLogout;
    private javax.swing.JMenuItem miRegister;
    private javax.swing.JPanel pInfo;
    private javax.swing.JPanel pToday;
    private javax.swing.JTable tbHistory;
    private javax.swing.JTabbedPane tpMenu;
    private javax.swing.JTextPane tpText;
    // End of variables declaration//GEN-END:variables
}
