/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import ProcessSocket.Client;
import Entity.Question;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.FlowLayout;
import java.awt.Font;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Vector;
import javax.swing.ButtonGroup;
import javax.swing.ButtonModel;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.Timer;

/**
 *
 * @author Hung
 */
public class frmTest extends javax.swing.JFrame {

    private Vector<ButtonGroup> vtBtGroup;
    private Vector<String> vtAnswer;

    private Timer dongho = null;
    private int timeRemain = 300;
    private frmMain frmMain;
    private Client client = new Client();
    private Vector<Question> vtQuestion = new Vector<>();
    private final int MAX = 10;

    String html = "<html><body style='width:180px'>";
    String html2 = "<html><body style='width:360px'>";

    JLabel[] label = new JLabel[5 * MAX];
    JPanel[] pnlMain = new JPanel[MAX];
    JPanel[] pnlTop = new JPanel[MAX];
    JPanel[] pnlCenter = new JPanel[MAX];

    public frmTest(Client client, frmMain frmMain, Vector<Question> vtQuestion) {
        this.client = client;
        this.frmMain = frmMain;
        this.vtQuestion = vtQuestion;
        initComponents();
        setInformation();
        setButtonGroupArr();
        this.setLocation(300, 20);
        countDown();
        loadQuestion();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    public void loadQuestion() {
        Color color = Color.WHITE;
        String fonts = "Times New Roman";
        int size = 16;
        pnlRoot.setBackground(color);

        for (int i = 0; i < MAX; i++) {
            Question ques = vtQuestion.get(i);

            pnlMain[i] = new JPanel(new BorderLayout());
            pnlMain[i].setSize(490, 150);
            pnlTop[i] = new JPanel(new FlowLayout(0));
            pnlCenter[i] = new JPanel(new GridLayout(2, 2, 5, 10));

            label[2 * i] = new JLabel(html2 + "Câu " + (i + 1) + ": " + ques.getQuestion());
            label[2 * i].setFont(new Font(fonts, 1, size));
            label[2 * i].setForeground(new Color(0, 0, 255));

            label[2 * i + 1] = new JLabel(html + "<b>A.</b> " + ques.getAnswerA());
            label[2 * i + 1].setFont(new Font(fonts, 0, size));
            label[2 * i + 1].setForeground(new Color(0, 0, 0));

            label[2 * i + 2] = new JLabel(html + "<b>B.</b> " + ques.getAnswerB());
            label[2 * i + 2].setFont(new Font(fonts, 0, size));
            label[2 * i + 2].setForeground(new Color(0, 0, 0));

            label[2 * i + 3] = new JLabel(html + "<b>C.</b> " + ques.getAnswerC());
            label[2 * i + 3].setFont(new Font(fonts, 0, size));
            label[2 * i + 3].setForeground(new Color(0, 0, 0));

            label[2 * i + 4] = new JLabel(html + "<b>D.</b> " + ques.getAnswerD());
            label[2 * i + 4].setFont(new Font(fonts, 0, size));
            label[2 * i + 4].setForeground(new Color(0, 0, 0));

            pnlTop[i].add(label[2 * i]);
            pnlCenter[i].add(label[2 * i + 1], 0);
            pnlCenter[i].add(label[2 * i + 2], 1);
            pnlCenter[i].add(label[2 * i + 3], 2);
            pnlCenter[i].add(label[2 * i + 4], 3);

            pnlTop[i].setBackground(color);
            pnlCenter[i].setBackground(color);
            pnlMain[i].setBackground(color);

            pnlMain[i].add(pnlTop[i], BorderLayout.NORTH);
            pnlMain[i].add(pnlCenter[i], BorderLayout.CENTER);
            pnlRoot.add(pnlMain[i]);
        }

    }


    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        buttonGroup7 = new javax.swing.ButtonGroup();
        buttonGroup8 = new javax.swing.ButtonGroup();
        buttonGroup9 = new javax.swing.ButtonGroup();
        buttonGroup10 = new javax.swing.ButtonGroup();
        buttonGroup11 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lbRemain = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jCheckBox7 = new javax.swing.JCheckBox();
        jCheckBox8 = new javax.swing.JCheckBox();
        jCheckBox9 = new javax.swing.JCheckBox();
        jCheckBox10 = new javax.swing.JCheckBox();
        jCheckBox11 = new javax.swing.JCheckBox();
        jCheckBox12 = new javax.swing.JCheckBox();
        jCheckBox13 = new javax.swing.JCheckBox();
        jCheckBox14 = new javax.swing.JCheckBox();
        jCheckBox15 = new javax.swing.JCheckBox();
        jCheckBox16 = new javax.swing.JCheckBox();
        jCheckBox17 = new javax.swing.JCheckBox();
        jCheckBox18 = new javax.swing.JCheckBox();
        jCheckBox19 = new javax.swing.JCheckBox();
        jCheckBox20 = new javax.swing.JCheckBox();
        jCheckBox21 = new javax.swing.JCheckBox();
        jCheckBox22 = new javax.swing.JCheckBox();
        jCheckBox23 = new javax.swing.JCheckBox();
        jCheckBox24 = new javax.swing.JCheckBox();
        jCheckBox25 = new javax.swing.JCheckBox();
        jCheckBox26 = new javax.swing.JCheckBox();
        jCheckBox27 = new javax.swing.JCheckBox();
        jCheckBox28 = new javax.swing.JCheckBox();
        jCheckBox29 = new javax.swing.JCheckBox();
        jCheckBox30 = new javax.swing.JCheckBox();
        jCheckBox31 = new javax.swing.JCheckBox();
        jCheckBox32 = new javax.swing.JCheckBox();
        jCheckBox33 = new javax.swing.JCheckBox();
        jCheckBox34 = new javax.swing.JCheckBox();
        jCheckBox35 = new javax.swing.JCheckBox();
        jCheckBox36 = new javax.swing.JCheckBox();
        jCheckBox37 = new javax.swing.JCheckBox();
        jCheckBox38 = new javax.swing.JCheckBox();
        jCheckBox39 = new javax.swing.JCheckBox();
        jCheckBox40 = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lbName = new javax.swing.JLabel();
        lbUsername = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbSubject = new javax.swing.JLabel();
        lbLevel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btCancel = new javax.swing.JButton();
        pnlQuestion = new javax.swing.JScrollPane();
        pnlRoot = new javax.swing.JPanel();
        btSubmit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, null, new java.awt.Color(153, 153, 255)));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("Thời gian còn lại:");

        lbRemain.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbRemain.setForeground(new java.awt.Color(255, 0, 0));
        lbRemain.setText("15:00");

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setText("Câu");

        jLabel9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel9.setText("Chọn đáp án");

        jLabel10.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel10.setText("1");

        jLabel11.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel11.setText("2");

        jLabel12.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel12.setText("3");

        jLabel13.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel13.setText("4");

        jLabel14.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel14.setText("5");

        jLabel15.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel15.setText("10");

        jLabel16.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel16.setText("9");

        jLabel17.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel17.setText("8");

        jLabel18.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel18.setText("7");

        jLabel19.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel19.setText("6");

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        buttonGroup1.add(jCheckBox1);
        jCheckBox1.setText("A");
        jCheckBox1.setActionCommand("" + (char) 65);

        buttonGroup1.add(jCheckBox2);
        jCheckBox2.setText("B");
        jCheckBox2.setActionCommand("" + (char) 66);

        buttonGroup1.add(jCheckBox3);
        jCheckBox3.setText("C");
        jCheckBox3.setActionCommand("" + (char) 67);

        buttonGroup1.add(jCheckBox4);
        jCheckBox4.setText("D");
        jCheckBox4.setActionCommand("" + (char) 68);

        buttonGroup2.add(jCheckBox5);
        jCheckBox5.setText("A");
        jCheckBox5.setActionCommand("" + (char) 65);

        buttonGroup2.add(jCheckBox6);
        jCheckBox6.setText("B");
        jCheckBox6.setActionCommand("" + (char) 66);

        buttonGroup2.add(jCheckBox7);
        jCheckBox7.setText("C");
        jCheckBox7.setActionCommand("" + (char) 67);

        buttonGroup2.add(jCheckBox8);
        jCheckBox8.setText("D");
        jCheckBox8.setActionCommand("" + (char) 68);

        buttonGroup3.add(jCheckBox9);
        jCheckBox9.setText("A");
        jCheckBox9.setActionCommand("" + (char) 65);

        buttonGroup3.add(jCheckBox10);
        jCheckBox10.setText("B");
        jCheckBox10.setActionCommand("" + (char) 66);

        buttonGroup3.add(jCheckBox11);
        jCheckBox11.setText("C");
        jCheckBox11.setActionCommand("" + (char) 67);

        buttonGroup3.add(jCheckBox12);
        jCheckBox12.setText("D");
        jCheckBox12.setActionCommand("" + (char) 68);

        buttonGroup4.add(jCheckBox13);
        jCheckBox13.setText("A");
        jCheckBox13.setActionCommand("" + (char) 65);

        buttonGroup4.add(jCheckBox14);
        jCheckBox14.setText("B");
        jCheckBox14.setActionCommand("" + (char) 66);

        buttonGroup4.add(jCheckBox15);
        jCheckBox15.setText("C");
        jCheckBox15.setActionCommand("" + (char) 67);

        buttonGroup4.add(jCheckBox16);
        jCheckBox16.setText("D");
        jCheckBox16.setActionCommand("" + (char) 68);

        buttonGroup5.add(jCheckBox17);
        jCheckBox17.setText("A");
        jCheckBox17.setActionCommand("" + (char) 65);

        buttonGroup5.add(jCheckBox18);
        jCheckBox18.setText("B");
        jCheckBox18.setActionCommand("" + (char) 66);

        buttonGroup5.add(jCheckBox19);
        jCheckBox19.setText("C");
        jCheckBox19.setActionCommand("" + (char) 67);

        buttonGroup5.add(jCheckBox20);
        jCheckBox20.setText("D");
        jCheckBox20.setActionCommand("" + (char) 68);

        buttonGroup6.add(jCheckBox21);
        jCheckBox21.setText("A");
        jCheckBox21.setActionCommand("" + (char) 65);

        buttonGroup6.add(jCheckBox22);
        jCheckBox22.setText("B");
        jCheckBox22.setActionCommand("" + (char) 66);

        buttonGroup6.add(jCheckBox23);
        jCheckBox23.setText("C");
        jCheckBox23.setActionCommand("" + (char) 67);

        buttonGroup6.add(jCheckBox24);
        jCheckBox24.setText("D");
        jCheckBox24.setActionCommand("" + (char) 68);

        buttonGroup7.add(jCheckBox25);
        jCheckBox25.setText("A");
        jCheckBox25.setActionCommand("" + (char) 65);

        buttonGroup7.add(jCheckBox26);
        jCheckBox26.setText("B");
        jCheckBox26.setActionCommand("" + (char) 66);

        buttonGroup7.add(jCheckBox27);
        jCheckBox27.setText("C");
        jCheckBox27.setActionCommand("" + (char) 67);

        buttonGroup7.add(jCheckBox28);
        jCheckBox28.setText("D");
        jCheckBox28.setActionCommand("" + (char) 68);

        buttonGroup8.add(jCheckBox29);
        jCheckBox29.setText("A");
        jCheckBox29.setActionCommand("" + (char) 65);

        buttonGroup8.add(jCheckBox30);
        jCheckBox30.setText("B");
        jCheckBox30.setActionCommand("" + (char) 66);

        buttonGroup8.add(jCheckBox31);
        jCheckBox31.setText("C");
        jCheckBox31.setActionCommand("" + (char) 67);

        buttonGroup8.add(jCheckBox32);
        jCheckBox32.setText("D");
        jCheckBox32.setActionCommand("" + (char) 68);

        buttonGroup9.add(jCheckBox33);
        jCheckBox33.setText("A");
        jCheckBox33.setActionCommand("" + (char) 65);

        buttonGroup9.add(jCheckBox34);
        jCheckBox34.setText("B");
        jCheckBox34.setActionCommand("" + (char) 66);

        buttonGroup9.add(jCheckBox35);
        jCheckBox35.setText("C");
        jCheckBox35.setActionCommand("" + (char) 67);

        buttonGroup9.add(jCheckBox36);
        jCheckBox36.setText("D");
        jCheckBox36.setActionCommand("" + (char) 68);

        buttonGroup10.add(jCheckBox37);
        jCheckBox37.setText("A");
        jCheckBox37.setActionCommand("" + (char) 65);

        buttonGroup10.add(jCheckBox38);
        jCheckBox38.setText("B");
        jCheckBox38.setActionCommand("" + (char) 66);

        buttonGroup10.add(jCheckBox39);
        jCheckBox39.setText("C");
        jCheckBox39.setActionCommand("" + (char) 67);

        buttonGroup10.add(jCheckBox40);
        jCheckBox40.setText("D");
        jCheckBox40.setActionCommand("" + (char) 68);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(21, 21, 21))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jSeparator1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel10)
                                .addComponent(jLabel12)
                                .addComponent(jLabel13)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel14)
                                .addComponent(jLabel19))
                            .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18)
                            .addComponent(jLabel16))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jCheckBox17)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jCheckBox18)
                                    .addGap(2, 2, 2)
                                    .addComponent(jCheckBox19)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jCheckBox20))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jCheckBox21)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jCheckBox22)
                                    .addGap(2, 2, 2)
                                    .addComponent(jCheckBox23)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jCheckBox24))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jCheckBox25)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jCheckBox26)
                                    .addGap(2, 2, 2)
                                    .addComponent(jCheckBox27)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jCheckBox28))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jCheckBox29)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jCheckBox30)
                                    .addGap(2, 2, 2)
                                    .addComponent(jCheckBox31)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jCheckBox32))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jCheckBox33)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jCheckBox34)
                                    .addGap(2, 2, 2)
                                    .addComponent(jCheckBox35)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jCheckBox36)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jCheckBox37)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox38)
                                .addGap(2, 2, 2)
                                .addComponent(jCheckBox39)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox40))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jCheckBox13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox14)
                                .addGap(2, 2, 2)
                                .addComponent(jCheckBox15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox16))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jCheckBox9)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jCheckBox10)
                                    .addGap(2, 2, 2)
                                    .addComponent(jCheckBox11)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jCheckBox12))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jCheckBox5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jCheckBox6)
                                        .addGap(2, 2, 2)
                                        .addComponent(jCheckBox7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jCheckBox8))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jCheckBox1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jCheckBox2)
                                        .addGap(2, 2, 2)
                                        .addComponent(jCheckBox3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jCheckBox4)))))))
                .addGap(19, 19, 19))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbRemain)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lbRemain))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox1)
                    .addComponent(jCheckBox2)
                    .addComponent(jCheckBox3)
                    .addComponent(jCheckBox4)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox5)
                    .addComponent(jCheckBox6)
                    .addComponent(jCheckBox7)
                    .addComponent(jCheckBox8)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox9)
                    .addComponent(jCheckBox10)
                    .addComponent(jCheckBox11)
                    .addComponent(jCheckBox12)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox13)
                    .addComponent(jCheckBox14)
                    .addComponent(jCheckBox15)
                    .addComponent(jCheckBox16)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jCheckBox17)
                    .addComponent(jCheckBox18)
                    .addComponent(jCheckBox19)
                    .addComponent(jCheckBox20))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox21)
                    .addComponent(jCheckBox22)
                    .addComponent(jCheckBox23)
                    .addComponent(jCheckBox24)
                    .addComponent(jLabel19))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox25)
                    .addComponent(jCheckBox26)
                    .addComponent(jCheckBox27)
                    .addComponent(jCheckBox28)
                    .addComponent(jLabel18))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox29)
                    .addComponent(jCheckBox30)
                    .addComponent(jCheckBox31)
                    .addComponent(jCheckBox32)
                    .addComponent(jLabel17))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox33)
                    .addComponent(jCheckBox34)
                    .addComponent(jCheckBox35)
                    .addComponent(jCheckBox36)
                    .addComponent(jLabel16))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox37)
                    .addComponent(jCheckBox38)
                    .addComponent(jCheckBox39)
                    .addComponent(jCheckBox40)
                    .addComponent(jLabel15))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("BÀI THI TRẮC NGHIỆM MÔN: ");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setText("Độ khó:");

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(153, 153, 255)), "Thông tin thí sinh", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14), new java.awt.Color(51, 51, 255))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel6.setText("Tài khoản:");

        jLabel7.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel7.setText("Họ và tên:");

        lbName.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lbName.setForeground(new java.awt.Color(255, 0, 0));
        lbName.setText("Name");

        lbUsername.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lbUsername.setForeground(new java.awt.Color(255, 0, 0));
        lbUsername.setText("Username");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbUsername))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbName)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lbUsername))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lbName))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("Thời gian làm bài:");

        lbSubject.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lbSubject.setForeground(new java.awt.Color(0, 102, 0));
        lbSubject.setText("SUBJECT");

        lbLevel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbLevel.setForeground(new java.awt.Color(0, 102, 0));
        lbLevel.setText("Level");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setText("15 phút");

        btCancel.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btCancel.setText("Bỏ bài");
        btCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelActionPerformed(evt);
            }
        });

        pnlRoot.setLayout(new java.awt.GridLayout(11, 1, 10, 30));
        pnlQuestion.setViewportView(pnlRoot);

        btSubmit.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btSubmit.setText("Nộp bài");
        btSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSubmitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbSubject))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbLevel)
                                .addGap(101, 101, 101)
                                .addComponent(jLabel2)
                                .addGap(14, 14, 14)
                                .addComponent(jLabel5)))
                        .addGap(0, 117, Short.MAX_VALUE))
                    .addComponent(pnlQuestion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(btSubmit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btCancel)
                        .addGap(44, 44, 44))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbSubject))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(lbLevel)
                            .addComponent(jLabel5))
                        .addGap(27, 27, 27)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btCancel)
                            .addComponent(btSubmit))
                        .addContainerGap())
                    .addComponent(pnlQuestion)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void setInformation() {
        lbSubject.setText(frmMain.subject);
        lbLevel.setText(frmMain.level);
        lbName.setText(frmMain.getFullname());
        lbUsername.setText(frmMain.getUsername());
    }

    private void countDown() {
        dongho = new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (--timeRemain >= 0) {
                    int i = timeRemain / 60;
                    int j = timeRemain - i * 60;
                    lbRemain.setText(((i > 9) ? ("" + i) : ("0" + i)) + " : " + ((j > 9) ? ("" + j) : ("0" + j)));
                } else {
                    JOptionPane.showMessageDialog(null, "Hết giờ. Bài thi đã tự động được gửi!");  
                    btCancel.setText("Quay lại");
                    dongho.stop();
                    showResult();
                }
            }
        });
        dongho.start();
    }

    private void setButtonGroupArr() {
        vtBtGroup = new Vector<>();
        vtBtGroup.add(buttonGroup1);
        vtBtGroup.add(buttonGroup2);
        vtBtGroup.add(buttonGroup3);
        vtBtGroup.add(buttonGroup4);
        vtBtGroup.add(buttonGroup5);
        vtBtGroup.add(buttonGroup6);
        vtBtGroup.add(buttonGroup7);
        vtBtGroup.add(buttonGroup8);
        vtBtGroup.add(buttonGroup9);
        vtBtGroup.add(buttonGroup10);
    }

    @SuppressWarnings("Testing")
    public void getAnswer() {
        vtAnswer = new Vector<>();
        for (int i = 0; i < vtBtGroup.size(); i++) {
            ButtonModel bt = vtBtGroup.get(i).getSelection();
            if (bt == null) {
                vtAnswer.add(null);
            } else {
                String ans = bt.getActionCommand();
                vtAnswer.add(ans);
            }
        }
    }

    @SuppressWarnings("Testing")
    public void showResult() {
        getAnswer();
        int total = client.reqSubmit(vtAnswer);
        String msg;
        if (total < 5) {
            msg = "Bài làm còn kém. Cần nỗ lực hơn nữa.";
        } else if (total < 7) {
            msg = "Trình độ ở mức trung bình. Cần phấn đấu thêm.";
        } else if (total < 9) {
            msg = "Nói chung là cũng giỏi đấy. Cơ mà chưa bằng hungdh.";
        } else {
            msg = "Ngồi ngay ngắn để admin lạy bạn một lạy";
        }
        JOptionPane.showMessageDialog(null, "<html>" + msg + "<br>" + "Tổng điểm: <b>" + total + "/10</b>");
    }

    private void btSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSubmitActionPerformed
        if (dongho.isRunning()) {
            int choice = JOptionPane.showConfirmDialog(null, "Hãy kiểm tra lại tất cả trước khi nộp bài.\n Bạn vẫn muốn nộp bài??", "Thông báo", JOptionPane.YES_NO_OPTION);
            if (choice == JOptionPane.YES_OPTION) {
                dongho.stop();
                showResult();
                btCancel.setText("Quay lại");
            }
        }
    }//GEN-LAST:event_btSubmitActionPerformed

    private void btCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelActionPerformed
        int choice = 5;
        if (dongho.isRunning()) {
            choice = JOptionPane.showConfirmDialog(null, "Nêu bỏ bài bạn sẽ không có điểm. Bạn chấp nhận chứ?", "Thông báo", JOptionPane.YES_NO_OPTION);
            if (choice == JOptionPane.YES_OPTION) {
                dongho.stop();
                btCancel.setText("Quay lại");
            }
        } else {
            choice = JOptionPane.showConfirmDialog(null, "Bạn muốn quay lại màn hình chính??", "Thông báo", JOptionPane.YES_NO_OPTION);
            if (choice == JOptionPane.YES_OPTION) {
                this.dispose();
                frmMain.setVisible(true);
            }
        }
    }//GEN-LAST:event_btCancelActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        int choice = 5;
        if (dongho.isRunning()) {
            choice = JOptionPane.showConfirmDialog(null, "Nêu bỏ bài bạn sẽ không có điểm. Bạn chấp nhận chứ?", "Thông báo", JOptionPane.YES_NO_OPTION);
        } else {
            choice = JOptionPane.showConfirmDialog(null, "Bạn muốn quay lại màn hình chính??", "Thông báo", JOptionPane.YES_NO_OPTION);
        }
        if (choice == JOptionPane.YES_OPTION) {
            this.dispose();
            frmMain.setVisible(true);
        }
    }//GEN-LAST:event_formWindowClosing

    public static void main(String[] args) {
        new frmTest(null, null, null).setVisible(true);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCancel;
    private javax.swing.JButton btSubmit;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup10;
    private javax.swing.ButtonGroup buttonGroup11;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.ButtonGroup buttonGroup7;
    private javax.swing.ButtonGroup buttonGroup8;
    private javax.swing.ButtonGroup buttonGroup9;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox10;
    private javax.swing.JCheckBox jCheckBox11;
    private javax.swing.JCheckBox jCheckBox12;
    private javax.swing.JCheckBox jCheckBox13;
    private javax.swing.JCheckBox jCheckBox14;
    private javax.swing.JCheckBox jCheckBox15;
    private javax.swing.JCheckBox jCheckBox16;
    private javax.swing.JCheckBox jCheckBox17;
    private javax.swing.JCheckBox jCheckBox18;
    private javax.swing.JCheckBox jCheckBox19;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox20;
    private javax.swing.JCheckBox jCheckBox21;
    private javax.swing.JCheckBox jCheckBox22;
    private javax.swing.JCheckBox jCheckBox23;
    private javax.swing.JCheckBox jCheckBox24;
    private javax.swing.JCheckBox jCheckBox25;
    private javax.swing.JCheckBox jCheckBox26;
    private javax.swing.JCheckBox jCheckBox27;
    private javax.swing.JCheckBox jCheckBox28;
    private javax.swing.JCheckBox jCheckBox29;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox30;
    private javax.swing.JCheckBox jCheckBox31;
    private javax.swing.JCheckBox jCheckBox32;
    private javax.swing.JCheckBox jCheckBox33;
    private javax.swing.JCheckBox jCheckBox34;
    private javax.swing.JCheckBox jCheckBox35;
    private javax.swing.JCheckBox jCheckBox36;
    private javax.swing.JCheckBox jCheckBox37;
    private javax.swing.JCheckBox jCheckBox38;
    private javax.swing.JCheckBox jCheckBox39;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox40;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JCheckBox jCheckBox8;
    private javax.swing.JCheckBox jCheckBox9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lbLevel;
    private javax.swing.JLabel lbName;
    private javax.swing.JLabel lbRemain;
    private javax.swing.JLabel lbSubject;
    private javax.swing.JLabel lbUsername;
    private javax.swing.JScrollPane pnlQuestion;
    private javax.swing.JPanel pnlRoot;
    // End of variables declaration//GEN-END:variables
}
