/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package History;

import Account.AccountDAO;
import Entity.History;
import Reports.Report;
import Submit.SubmitDAO;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Huy Hung
 */
public class panelHistory extends javax.swing.JPanel {

    private Vector<History> vtHistory = new Vector<History>();
    private AccountDAO accDAO = new AccountDAO();
    private SubmitDAO subDAO = new SubmitDAO();
    private String username;
    private String fullName;
    private DefaultTableModel model = new DefaultTableModel() {
        @Override
        public boolean isCellEditable(int rowIndex, int columnIndex) {
            return false;
        }
    };

    /**
     * Creates new form panelHistory
     */
    public panelHistory(String username, String fullName) {
        this.username = username;
        this.fullName = fullName;
        initComponents();
        loadColumnData();
        tfSearch.setText(username);
        btSearch.doClick();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tfSearch = new javax.swing.JTextField();
        btSearch = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        lbNum = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbHistory = new javax.swing.JTable();
        jLabel15 = new javax.swing.JLabel();
        cbSubjectHistory = new javax.swing.JComboBox();
        btPrint = new javax.swing.JButton();
        btUpdate = new javax.swing.JButton();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tìm Kiếm", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP));

        tfSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfSearchActionPerformed(evt);
            }
        });

        btSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Search.png"))); // NOI18N
        btSearch.setText("Tìm Kiếm");
        btSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSearchActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 204));
        jLabel2.setText("Username");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(tfSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel9.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel9.setText("Số bài thi đã làm:");

        lbNum.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lbNum.setForeground(new java.awt.Color(255, 0, 0));
        lbNum.setText("5");

        tbHistory.setAutoCreateRowSorter(true);
        tbHistory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbHistory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tbHistoryMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tbHistory);

        jLabel15.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel15.setText("Hiển thị theo môn thi:");

        cbSubjectHistory.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "[---Tất cả---]", "Tiếng Anh", "Mạng Máy Tính" }));
        cbSubjectHistory.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cbSubjectHistory.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbSubjectHistoryItemStateChanged(evt);
            }
        });
        cbSubjectHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSubjectHistoryActionPerformed(evt);
            }
        });

        btPrint.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btPrint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/printer_3.png"))); // NOI18N
        btPrint.setText("In chi tiết");
        btPrint.setEnabled(false);
        btPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPrintActionPerformed(evt);
            }
        });

        btUpdate.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Refresh.png"))); // NOI18N
        btUpdate.setText("Cập nhật");
        btUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btPrint)
                .addGap(39, 39, 39)
                .addComponent(btUpdate)
                .addGap(206, 206, 206))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel16))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lbNum)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(18, 18, 18)
                        .addComponent(cbSubjectHistory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(lbNum))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbSubjectHistory, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btUpdate)
                    .addComponent(btPrint)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 180, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tfSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfSearchActionPerformed
        btSearch.doClick();
    }//GEN-LAST:event_tfSearchActionPerformed

    private void btSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSearchActionPerformed
        btPrint.setEnabled(false);
        if (tfSearch.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Khung tìm kiếm không được để trống.", "  Lỗi Tìm Kiếm   ", 0);
        } else {
            if (accDAO.checkUser(tfSearch.getText())) {
                vtHistory = subDAO.getHistory(tfSearch.getText());
                loadRowData();
            } else {
                JOptionPane.showMessageDialog(null, "<html>Username <b>" + tfSearch.getText() + "</b> không tồn tại.");
            }
        }
    }//GEN-LAST:event_btSearchActionPerformed

    private void loadColumnData() {
        Vector<String> columnName = new Vector();
        columnName.add(0, "STT");
        columnName.add(1, "Môn thi");
        columnName.add(2, "Độ khó");
        columnName.add(3, "Thời gian");
        columnName.add(4, "Điểm");
        model.setColumnIdentifiers(columnName);
    }

    private void loadRowData() {
        int stt = 0;
        removeRow();
        int num = vtHistory.size();
        if (num > 0) {
            lbNum.setText(num + "");
        } else {
            lbNum.setText("0");
        }

        for (History hs : vtHistory) {
            stt++;
            model.addRow(toObjectData(stt, hs));
        }
        tbHistory.setModel(model);
    }
    private void cbSubjectHistoryItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbSubjectHistoryItemStateChanged
        if (cbSubjectHistory.getSelectedIndex() != 0) {
            removeRow();
            int stt = 0;
            for (History hs : vtHistory) {
                if (hs.getNameSubject().equalsIgnoreCase(cbSubjectHistory.getSelectedItem().toString())) {
                    stt++;
                    model.addRow(toObjectData(stt, hs));
                }
            }
            if (stt == 0) {
                JOptionPane.showMessageDialog(null, "Bạn chưa thi môn này lần nào.", "Thông báo", 1);
            }
            tbHistory.setModel(model);
        } else {
            loadRowData();
        }
    }//GEN-LAST:event_cbSubjectHistoryItemStateChanged

    private void btUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btUpdateActionPerformed
        btSearch.doClick();
    }//GEN-LAST:event_btUpdateActionPerformed

    private void removeRow() {
        while (model.getRowCount() > 0) {
            model.removeRow(0);
        }
    }

    private Object[] toObjectData(int stt, History hs) {
        Object[] obj = {stt, hs.getNameSubject(), hs.getLevel(), hs.getTimeTask(), hs.getTotal()};
        return obj;
    }
    private void cbSubjectHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSubjectHistoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbSubjectHistoryActionPerformed

    private void tbHistoryMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbHistoryMouseReleased
        btPrint.setEnabled(true);
    }//GEN-LAST:event_tbHistoryMouseReleased

    private void btPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPrintActionPerformed
        int idTask = vtHistory.get(tbHistory.getSelectedRow()).getIdTask();
        String subject = tbHistory.getValueAt(tbHistory.getSelectedRow(), 1).toString();
        String level = tbHistory.getValueAt(tbHistory.getSelectedRow(), 2).toString();
        String time = tbHistory.getValueAt(tbHistory.getSelectedRow(), 3).toString();
        int total = Integer.parseInt(tbHistory.getValueAt(tbHistory.getSelectedRow(), 4).toString());
        new Report(idTask, fullName, subject, level, time, total).createReport();
    }//GEN-LAST:event_btPrintActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btPrint;
    private javax.swing.JButton btSearch;
    private javax.swing.JButton btUpdate;
    private javax.swing.JComboBox cbSubjectHistory;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbNum;
    private javax.swing.JTable tbHistory;
    private javax.swing.JTextField tfSearch;
    // End of variables declaration//GEN-END:variables
}
